// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmfgpmarxibrodbajxif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZmdwbWFyeGlicm9kYmFqeGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzYwNDcsImV4cCI6MjA2NTkxMjA0N30.zFiE9QEcy3D92uAFx6dl4TJs6iLnsxan5zio0xlDWkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);